2023-05-15 08:43:05,323 INFO Watching for file changes with StatReloader
2023-05-15 08:43:36,455 INFO Watching for file changes with StatReloader
2023-05-15 08:45:36,070 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 08:45:36,669 INFO Watching for file changes with StatReloader
2023-05-15 08:47:05,746 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 08:47:06,342 INFO Watching for file changes with StatReloader
2023-05-15 08:47:13,822 ERROR something went wrong
2023-05-15 08:56:43,917 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 08:56:44,501 INFO Watching for file changes with StatReloader
2023-05-15 08:57:32,885 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 08:57:33,453 INFO Watching for file changes with StatReloader
2023-05-15 08:57:36,072 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 08:57:36,664 INFO Watching for file changes with StatReloader
2023-05-15 08:59:59,326 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 08:59:59,920 INFO Watching for file changes with StatReloader
2023-05-15 09:00:07,277 ERROR something went wrong
2023-05-15 09:00:24,930 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:00:25,493 INFO Watching for file changes with StatReloader
2023-05-15 09:00:50,735 ERROR something went wrong
2023-05-15 09:01:48,374 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:01:48,943 INFO Watching for file changes with StatReloader
2023-05-15 09:01:51,897 ERROR something went wrong
2023-05-15 09:01:51,897 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 09:02:12,978 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:02:13,559 INFO Watching for file changes with StatReloader
2023-05-15 09:02:27,511 ERROR something went wrong
2023-05-15 09:02:57,877 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:02:58,473 INFO Watching for file changes with StatReloader
2023-05-15 09:03:05,641 ERROR something went wrong
2023-05-15 09:03:49,022 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:03:49,593 INFO Watching for file changes with StatReloader
2023-05-15 09:05:08,559 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:05:09,155 INFO Watching for file changes with StatReloader
2023-05-15 09:05:23,998 ERROR something went wrong
2023-05-15 09:07:20,989 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:07:21,599 INFO Watching for file changes with StatReloader
2023-05-15 09:07:41,196 ERROR something went wrong
2023-05-15 09:10:02,888 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:10:03,467 INFO Watching for file changes with StatReloader
2023-05-15 09:11:51,803 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:11:52,389 INFO Watching for file changes with StatReloader
2023-05-15 09:12:00,510 ERROR something went wrong
2023-05-15 09:12:08,897 ERROR something went wrong
2023-05-15 09:12:47,061 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:12:47,711 INFO Watching for file changes with StatReloader
2023-05-15 09:12:50,461 INFO Watching for file changes with StatReloader
2023-05-15 09:13:14,461 INFO Watching for file changes with StatReloader
2023-05-15 09:13:32,526 ERROR something went wrong
2023-05-15 09:14:32,424 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:14:33,015 INFO Watching for file changes with StatReloader
2023-05-15 09:14:51,000 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 09:14:51,578 INFO Watching for file changes with StatReloader
2023-05-15 09:15:02,357 ERROR Internal Server Error: /admin/frontapp/exceptions/3/change/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
                ^^^^^^^^
TypeError: __str__ returned non-string (type User)
2023-05-15 09:15:12,556 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:15:13,215 INFO Watching for file changes with StatReloader
2023-05-15 09:19:10,472 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:19:11,111 INFO Watching for file changes with StatReloader
2023-05-15 09:19:24,756 ERROR something went wrong
2023-05-15 09:20:15,802 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:20:16,383 INFO Watching for file changes with StatReloader
2023-05-15 09:20:19,665 ERROR Internal Server Error: /admin/frontapp/exceptions/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Exceptions has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 285, in lookup_field
    value = attr()
            ^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py", line 104, in __str__
    return self.user_id + str(self.user_id)
           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'User' and 'str'
2023-05-15 09:20:25,132 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:20:25,672 INFO Watching for file changes with StatReloader
2023-05-15 09:21:23,306 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:21:23,782 INFO Watching for file changes with StatReloader
2023-05-15 09:21:37,601 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:21:38,184 INFO Watching for file changes with StatReloader
2023-05-15 09:21:39,764 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:21:40,352 INFO Watching for file changes with StatReloader
2023-05-15 09:21:50,130 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:21:50,737 INFO Watching for file changes with StatReloader
2023-05-15 09:21:57,427 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:21:58,008 INFO Watching for file changes with StatReloader
2023-05-15 09:22:04,722 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 09:22:05,301 INFO Watching for file changes with StatReloader
2023-05-15 09:25:26,937 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:25:27,506 INFO Watching for file changes with StatReloader
2023-05-15 09:25:41,254 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:25:41,826 INFO Watching for file changes with StatReloader
2023-05-15 09:26:27,101 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:26:27,716 INFO Watching for file changes with StatReloader
2023-05-15 09:26:45,923 ERROR something went wrong
2023-05-15 09:27:30,441 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:27:31,031 INFO Watching for file changes with StatReloader
2023-05-15 09:27:40,784 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:27:41,383 INFO Watching for file changes with StatReloader
2023-05-15 09:27:51,244 ERROR something went wrong
2023-05-15 09:29:00,390 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:29:00,964 INFO Watching for file changes with StatReloader
2023-05-15 09:29:10,510 ERROR something went wrong
2023-05-15 09:30:05,697 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:30:06,322 INFO Watching for file changes with StatReloader
2023-05-15 09:30:13,090 ERROR something went wrong
2023-05-15 09:30:57,921 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:30:58,505 INFO Watching for file changes with StatReloader
2023-05-15 09:31:09,242 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:31:09,820 INFO Watching for file changes with StatReloader
2023-05-15 09:31:25,042 ERROR something went wrong
2023-05-15 09:32:47,114 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:32:47,691 INFO Watching for file changes with StatReloader
2023-05-15 09:32:59,334 ERROR something went wrong
2023-05-15 09:39:00,939 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:39:01,553 INFO Watching for file changes with StatReloader
2023-05-15 09:39:10,267 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:39:10,857 INFO Watching for file changes with StatReloader
2023-05-15 09:39:14,219 INFO Watching for file changes with StatReloader
2023-05-15 09:39:24,770 ERROR something went wrong
2023-05-15 09:39:48,576 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:39:49,151 INFO Watching for file changes with StatReloader
2023-05-15 09:39:58,900 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:39:59,520 INFO Watching for file changes with StatReloader
2023-05-15 09:40:10,955 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:40:11,482 INFO Watching for file changes with StatReloader
2023-05-15 09:41:14,765 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:41:15,309 INFO Watching for file changes with StatReloader
2023-05-15 09:41:26,571 ERROR something went wrong
2023-05-15 09:42:06,934 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:42:07,542 INFO Watching for file changes with StatReloader
2023-05-15 09:42:15,731 ERROR something went wrong
2023-05-15 09:43:08,213 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:43:08,788 INFO Watching for file changes with StatReloader
2023-05-15 09:43:14,413 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:43:14,987 INFO Watching for file changes with StatReloader
2023-05-15 09:44:07,335 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:07,907 INFO Watching for file changes with StatReloader
2023-05-15 09:44:11,537 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:12,117 INFO Watching for file changes with StatReloader
2023-05-15 09:44:26,959 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:27,541 INFO Watching for file changes with StatReloader
2023-05-15 09:44:31,162 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:31,756 INFO Watching for file changes with StatReloader
2023-05-15 09:44:33,316 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:33,899 INFO Watching for file changes with StatReloader
2023-05-15 09:44:41,588 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:44:42,165 INFO Watching for file changes with StatReloader
2023-05-15 09:45:16,297 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:45:16,869 INFO Watching for file changes with StatReloader
2023-05-15 09:45:24,410 ERROR something went wrong
2023-05-15 09:45:24,411 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 09:45:47,109 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:45:47,683 INFO Watching for file changes with StatReloader
2023-05-15 09:45:55,545 ERROR something went wrong
2023-05-15 09:45:55,545 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 09:46:15,841 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:46:16,437 INFO Watching for file changes with StatReloader
2023-05-15 09:46:28,179 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:46:28,751 INFO Watching for file changes with StatReloader
2023-05-15 09:47:58,711 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:47:59,279 INFO Watching for file changes with StatReloader
2023-05-15 09:48:19,146 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:48:19,716 INFO Watching for file changes with StatReloader
2023-05-15 09:48:45,746 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:48:46,354 INFO Watching for file changes with StatReloader
2023-05-15 09:48:56,006 ERROR something went wrong
2023-05-15 09:49:33,813 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:49:34,407 INFO Watching for file changes with StatReloader
2023-05-15 09:50:36,126 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:50:36,785 INFO Watching for file changes with StatReloader
2023-05-15 09:50:54,623 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:50:55,280 INFO Watching for file changes with StatReloader
2023-05-15 09:51:16,195 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:51:16,797 INFO Watching for file changes with StatReloader
2023-05-15 09:51:19,920 WARNING Not Found: /favicon.ico
2023-05-15 09:51:20,472 WARNING Not Found: /favicon.ico
2023-05-15 09:51:20,777 WARNING Not Found: /favicon.ico
2023-05-15 09:51:21,023 WARNING Not Found: /favicon.ico
2023-05-15 09:51:21,238 WARNING Not Found: /favicon.ico
2023-05-15 09:51:24,787 WARNING Not Found: /favicon.ico
2023-05-15 09:51:25,083 WARNING Not Found: /favicon.ico
2023-05-15 09:51:25,486 WARNING Not Found: /favicon.ico
2023-05-15 09:51:50,985 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:51:51,560 INFO Watching for file changes with StatReloader
2023-05-15 09:54:34,937 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:54:35,518 INFO Watching for file changes with StatReloader
2023-05-15 09:54:53,403 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:54:54,009 INFO Watching for file changes with StatReloader
2023-05-15 09:55:09,859 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:55:10,451 INFO Watching for file changes with StatReloader
2023-05-15 09:55:40,556 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:55:41,131 INFO Watching for file changes with StatReloader
2023-05-15 09:55:48,822 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 09:55:49,420 INFO Watching for file changes with StatReloader
2023-05-15 10:05:20,073 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:05:20,665 INFO Watching for file changes with StatReloader
2023-05-15 10:05:23,269 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:05:23,862 INFO Watching for file changes with StatReloader
2023-05-15 10:06:08,174 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:06:08,771 INFO Watching for file changes with StatReloader
2023-05-15 10:08:01,156 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:08:01,739 INFO Watching for file changes with StatReloader
2023-05-15 10:09:00,202 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:09:00,774 INFO Watching for file changes with StatReloader
2023-05-15 10:10:09,368 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:10:09,955 INFO Watching for file changes with StatReloader
2023-05-15 10:10:40,036 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 54, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 80, in login_user
    save_exception_to_database(
TypeError: save_exception_to_database() got an unexpected keyword argument 'type'
2023-05-15 10:11:16,654 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:11:17,256 INFO Watching for file changes with StatReloader
2023-05-15 10:11:25,479 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 92, in login_user
    save_exception_to_database(
TypeError: save_exception_to_database() got an unexpected keyword argument 'type'
2023-05-15 10:12:11,809 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:12:12,441 INFO Watching for file changes with StatReloader
2023-05-15 10:12:20,808 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 92, in login_user
    save_exception_to_database(
TypeError: save_exception_to_database() got an unexpected keyword argument 'type'
2023-05-15 10:17:35,126 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:17:35,745 INFO Watching for file changes with StatReloader
2023-05-15 10:18:18,031 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:18:18,648 INFO Watching for file changes with StatReloader
2023-05-15 10:18:26,339 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:18:26,904 INFO Watching for file changes with StatReloader
2023-05-15 10:18:35,925 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 95, in login_user
    save_exception_to_database(
TypeError: save_exception_to_database() got an unexpected keyword argument 'type'
2023-05-15 10:20:21,428 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:20:22,017 INFO Watching for file changes with StatReloader
2023-05-15 10:20:28,201 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 95, in login_user
    save_exception_to_database(
TypeError: save_exception_to_database() got an unexpected keyword argument 'messages'
2023-05-15 10:21:18,765 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:21:21,215 INFO Watching for file changes with StatReloader
2023-05-15 10:21:28,052 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 95, in login_user
    save_exception_to_database(
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 46, in save_exception_to_database
    user_id_instence = User.objects.get(id=user_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-05-15 10:21:56,516 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:21:57,094 INFO Watching for file changes with StatReloader
2023-05-15 10:23:10,783 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 10:23:11,378 INFO Watching for file changes with StatReloader
2023-05-15 10:23:36,840 INFO Watching for file changes with StatReloader
2023-05-15 10:24:20,133 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:24:20,711 INFO Watching for file changes with StatReloader
2023-05-15 10:24:33,817 ERROR Internal Server Error: /front/login/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 66, in login_user
    activity.save()
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: frontapp_useractivity.user_id_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 93, in login_user
    save_exception_to_database(
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 46, in save_exception_to_database
    user_id_instence = User.objects.get(id=user_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
2023-05-15 10:27:51,723 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:27:52,332 INFO Watching for file changes with StatReloader
2023-05-15 10:30:00,842 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:30:01,453 INFO Watching for file changes with StatReloader
2023-05-15 10:30:04,654 INFO Watching for file changes with StatReloader
2023-05-15 10:30:14,930 ERROR something went wrong
2023-05-15 10:30:28,757 ERROR something went wrong
2023-05-15 10:30:28,758 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:31:05,252 ERROR something went wrong
2023-05-15 10:31:05,252 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:31:40,031 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:31:40,617 INFO Watching for file changes with StatReloader
2023-05-15 10:31:43,146 WARNING Not Found: /front/forgot-password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 10:31:51,504 WARNING Not Found: /front/change_password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 10:32:02,687 ERROR something went wrong
2023-05-15 10:32:10,690 ERROR something went wrong
2023-05-15 10:32:10,690 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:32:15,562 WARNING Forbidden (CSRF token from POST incorrect.): /admin/login/
2023-05-15 10:32:19,264 WARNING Forbidden (CSRF token from POST incorrect.): /admin/login/
2023-05-15 10:32:19,277 WARNING Not Found: /favicon.ico
2023-05-15 10:32:22,232 WARNING Forbidden (CSRF token from POST incorrect.): /admin/login/
2023-05-15 10:32:22,280 WARNING Not Found: /favicon.ico
2023-05-15 10:32:41,492 ERROR something went wrong
2023-05-15 10:32:41,493 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:33:30,160 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:33:30,751 INFO Watching for file changes with StatReloader
2023-05-15 10:33:33,816 WARNING Not Found: /favicon.ico
2023-05-15 10:33:34,102 WARNING Not Found: /favicon.ico
2023-05-15 10:33:46,524 ERROR something went wrong
2023-05-15 10:33:46,524 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:34:35,630 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:34:36,209 INFO Watching for file changes with StatReloader
2023-05-15 10:34:40,997 INFO Watching for file changes with StatReloader
2023-05-15 10:34:51,172 ERROR something went wrong
2023-05-15 10:34:51,172 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:35:24,380 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:35:24,952 INFO Watching for file changes with StatReloader
2023-05-15 10:35:52,097 ERROR something went wrong
2023-05-15 10:35:52,097 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:35:57,762 ERROR something went wrong
2023-05-15 10:35:57,762 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:37:00,448 ERROR something went wrong
2023-05-15 10:37:00,449 ERROR An error occurred during login: cannot access local variable 'e' where it is not associated with a value
2023-05-15 10:39:09,319 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:39:09,926 INFO Watching for file changes with StatReloader
2023-05-15 10:39:15,579 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:39:16,184 INFO Watching for file changes with StatReloader
2023-05-15 10:39:28,949 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:39:29,513 INFO Watching for file changes with StatReloader
2023-05-15 10:39:35,157 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:39:35,781 INFO Watching for file changes with StatReloader
2023-05-15 10:41:53,743 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:41:54,337 INFO Watching for file changes with StatReloader
2023-05-15 10:42:43,817 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:42:44,418 INFO Watching for file changes with StatReloader
2023-05-15 10:42:47,351 INFO Watching for file changes with StatReloader
2023-05-15 10:43:48,048 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:43:48,623 INFO Watching for file changes with StatReloader
2023-05-15 10:43:59,375 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:43:59,944 INFO Watching for file changes with StatReloader
2023-05-15 10:44:10,645 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:44:11,223 INFO Watching for file changes with StatReloader
2023-05-15 10:45:35,246 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:45:35,825 INFO Watching for file changes with StatReloader
2023-05-15 10:45:39,953 INFO Watching for file changes with StatReloader
2023-05-15 10:46:18,239 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:46:18,813 INFO Watching for file changes with StatReloader
2023-05-15 10:46:42,829 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:46:43,397 INFO Watching for file changes with StatReloader
2023-05-15 10:46:49,044 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:46:49,618 INFO Watching for file changes with StatReloader
2023-05-15 10:47:56,238 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:47:56,827 INFO Watching for file changes with StatReloader
2023-05-15 10:50:31,931 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:50:32,492 INFO Watching for file changes with StatReloader
2023-05-15 10:50:53,387 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:50:53,971 INFO Watching for file changes with StatReloader
2023-05-15 10:51:00,649 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:51:01,237 INFO Watching for file changes with StatReloader
2023-05-15 10:51:26,209 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:51:26,802 INFO Watching for file changes with StatReloader
2023-05-15 10:51:51,742 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:51:52,338 INFO Watching for file changes with StatReloader
2023-05-15 10:53:11,214 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:53:11,843 INFO Watching for file changes with StatReloader
2023-05-15 10:54:58,041 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:54:58,611 INFO Watching for file changes with StatReloader
2023-05-15 10:56:11,587 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 10:56:12,183 INFO Watching for file changes with StatReloader
2023-05-15 10:56:14,461 WARNING Not Found: /favicon.ico
2023-05-15 10:57:13,906 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:57:14,487 INFO Watching for file changes with StatReloader
2023-05-15 10:58:22,185 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 10:58:22,818 INFO Watching for file changes with StatReloader
2023-05-15 11:02:34,400 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:02:35,010 INFO Watching for file changes with StatReloader
2023-05-15 11:03:46,887 WARNING Not Found: /front/change_password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 11:04:43,697 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:04:44,307 INFO Watching for file changes with StatReloader
2023-05-15 11:04:55,073 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:04:55,706 INFO Watching for file changes with StatReloader
2023-05-15 11:05:36,909 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:05:37,500 INFO Watching for file changes with StatReloader
2023-05-15 11:07:02,414 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:07:02,988 INFO Watching for file changes with StatReloader
2023-05-15 11:07:12,670 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:07:13,279 INFO Watching for file changes with StatReloader
2023-05-15 11:07:31,129 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:07:31,754 INFO Watching for file changes with StatReloader
2023-05-15 11:09:59,690 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:10:00,295 INFO Watching for file changes with StatReloader
2023-05-15 11:10:07,968 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:10:08,548 INFO Watching for file changes with StatReloader
2023-05-15 11:12:46,659 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:12:47,277 INFO Watching for file changes with StatReloader
2023-05-15 11:13:41,912 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:13:42,492 INFO Watching for file changes with StatReloader
2023-05-15 11:14:40,091 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:14:40,671 INFO Watching for file changes with StatReloader
2023-05-15 11:14:44,676 WARNING Not Found: /front/forgot-password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 11:14:59,960 WARNING Not Found: /front/change_password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 11:16:50,484 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 11:16:51,067 INFO Watching for file changes with StatReloader
2023-05-15 11:19:25,168 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:19:25,750 INFO Watching for file changes with StatReloader
2023-05-15 11:21:50,571 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:21:51,241 INFO Watching for file changes with StatReloader
2023-05-15 11:23:00,780 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:23:01,366 INFO Watching for file changes with StatReloader
2023-05-15 11:23:50,904 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:23:51,592 INFO Watching for file changes with StatReloader
2023-05-15 11:24:02,040 INFO Watching for file changes with StatReloader
2023-05-15 11:24:34,211 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 11:24:34,779 INFO Watching for file changes with StatReloader
2023-05-15 11:25:18,976 INFO Watching for file changes with StatReloader
2023-05-15 11:30:15,775 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:30:16,352 INFO Watching for file changes with StatReloader
2023-05-15 11:30:22,492 INFO Watching for file changes with StatReloader
2023-05-15 11:30:45,452 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 11:30:46,014 INFO Watching for file changes with StatReloader
2023-05-15 11:31:43,750 WARNING Not Found: /favicon.ico
2023-05-15 11:31:47,143 WARNING Not Found: /favicon.ico
2023-05-15 11:31:47,564 WARNING Not Found: /favicon.ico
2023-05-15 11:31:47,976 WARNING Not Found: /favicon.ico
2023-05-15 11:31:48,322 WARNING Not Found: /favicon.ico
2023-05-15 11:31:48,690 WARNING Not Found: /favicon.ico
2023-05-15 11:39:49,205 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:39:49,780 INFO Watching for file changes with StatReloader
2023-05-15 11:40:00,453 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:40:01,013 INFO Watching for file changes with StatReloader
2023-05-15 11:40:11,702 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:40:12,281 INFO Watching for file changes with StatReloader
2023-05-15 11:40:21,003 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:40:21,590 INFO Watching for file changes with StatReloader
2023-05-15 11:40:31,270 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:40:31,860 INFO Watching for file changes with StatReloader
2023-05-15 11:40:49,706 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:40:50,310 INFO Watching for file changes with StatReloader
2023-05-15 11:41:36,611 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:41:37,181 INFO Watching for file changes with StatReloader
2023-05-15 11:41:41,791 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:41:42,365 INFO Watching for file changes with StatReloader
2023-05-15 11:44:11,489 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 11:44:12,097 INFO Watching for file changes with StatReloader
2023-05-15 12:14:15,549 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:14:16,142 INFO Watching for file changes with StatReloader
2023-05-15 12:15:38,033 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:15:38,601 INFO Watching for file changes with StatReloader
2023-05-15 12:15:45,269 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:15:45,872 INFO Watching for file changes with StatReloader
2023-05-15 12:16:41,380 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:16:41,963 INFO Watching for file changes with StatReloader
2023-05-15 12:17:59,931 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/models.py changed, reloading.
2023-05-15 12:18:00,511 INFO Watching for file changes with StatReloader
2023-05-15 12:18:52,674 WARNING Not Found: /favicon.ico
2023-05-15 12:19:17,372 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 12:19:17,953 INFO Watching for file changes with StatReloader
2023-05-15 12:19:27,719 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/admin.py changed, reloading.
2023-05-15 12:19:28,293 INFO Watching for file changes with StatReloader
2023-05-15 12:19:43,078 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:19:43,649 INFO Watching for file changes with StatReloader
2023-05-15 12:19:46,240 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:19:46,814 INFO Watching for file changes with StatReloader
2023-05-15 12:19:52,451 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:19:53,036 INFO Watching for file changes with StatReloader
2023-05-15 12:19:56,673 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:19:57,277 INFO Watching for file changes with StatReloader
2023-05-15 12:19:59,882 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:20:00,463 INFO Watching for file changes with StatReloader
2023-05-15 12:20:43,690 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:20:44,252 INFO Watching for file changes with StatReloader
2023-05-15 12:20:49,582 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:20:50,097 INFO Watching for file changes with StatReloader
2023-05-15 12:21:11,966 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:21:12,536 INFO Watching for file changes with StatReloader
2023-05-15 12:21:23,242 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:21:23,813 INFO Watching for file changes with StatReloader
2023-05-15 12:21:35,318 ERROR Internal Server Error: /front/logout/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.logout_user didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:21:53,914 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:21:54,477 INFO Watching for file changes with StatReloader
2023-05-15 12:21:56,091 ERROR something went wrong
2023-05-15 12:21:56,626 ERROR something went wrong
2023-05-15 12:21:56,811 ERROR something went wrong
2023-05-15 12:22:22,469 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:22:23,037 INFO Watching for file changes with StatReloader
2023-05-15 12:22:25,148 ERROR something went wrong
2023-05-15 12:22:46,030 WARNING Forbidden (CSRF token from POST incorrect.): /front/login/
2023-05-15 12:22:48,590 WARNING Forbidden (CSRF token from POST incorrect.): /front/login/
2023-05-15 12:22:48,612 WARNING Not Found: /favicon.ico
2023-05-15 12:22:50,597 WARNING Forbidden (CSRF token from POST incorrect.): /front/login/
2023-05-15 12:22:50,611 WARNING Not Found: /favicon.ico
2023-05-15 12:22:57,019 ERROR Internal Server Error: /front/logout/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.logout_user didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:25:20,676 INFO Watching for file changes with StatReloader
2023-05-15 12:25:29,364 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:25:29,960 INFO Watching for file changes with StatReloader
2023-05-15 12:25:59,056 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:25:59,661 INFO Watching for file changes with StatReloader
2023-05-15 12:26:07,911 ERROR Internal Server Error: /front/logout/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.logout_user didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:26:15,501 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:26:16,077 INFO Watching for file changes with StatReloader
2023-05-15 12:26:28,849 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:26:29,420 INFO Watching for file changes with StatReloader
2023-05-15 12:27:09,613 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:27:10,200 INFO Watching for file changes with StatReloader
2023-05-15 12:28:59,585 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:29:00,170 INFO Watching for file changes with StatReloader
2023-05-15 12:30:39,506 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:30:40,085 INFO Watching for file changes with StatReloader
2023-05-15 12:30:56,952 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:30:57,560 INFO Watching for file changes with StatReloader
2023-05-15 12:31:01,741 INFO Watching for file changes with StatReloader
2023-05-15 12:31:04,366 WARNING Not Found: /favicon.ico
2023-05-15 12:31:04,802 WARNING Not Found: /favicon.ico
2023-05-15 12:31:05,031 WARNING Not Found: /favicon.ico
2023-05-15 12:31:05,348 WARNING Not Found: /favicon.ico
2023-05-15 12:31:06,143 WARNING Not Found: /favicon.ico
2023-05-15 12:36:16,878 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:36:17,474 INFO Watching for file changes with StatReloader
2023-05-15 12:37:02,637 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:37:03,200 INFO Watching for file changes with StatReloader
2023-05-15 12:37:26,117 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:37:26,696 INFO Watching for file changes with StatReloader
2023-05-15 12:37:57,812 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:37:58,371 INFO Watching for file changes with StatReloader
2023-05-15 12:39:01,914 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:39:02,483 INFO Watching for file changes with StatReloader
2023-05-15 12:41:33,451 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:41:34,088 INFO Watching for file changes with StatReloader
2023-05-15 12:41:54,988 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:41:55,564 INFO Watching for file changes with StatReloader
2023-05-15 12:43:07,455 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:43:08,070 INFO Watching for file changes with StatReloader
2023-05-15 12:44:06,600 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:45:14,837 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/urls.py changed, reloading.
2023-05-15 12:45:15,412 INFO Watching for file changes with StatReloader
2023-05-15 12:45:18,019 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:45:18,582 INFO Watching for file changes with StatReloader
2023-05-15 12:45:33,910 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:45:39,858 ERROR Internal Server Error: /front/home/
Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 541, in delete_multiple_product
    import acsd
ModuleNotFoundError: No module named 'acsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 575, in delete_multiple_product
    return render(request, "temp/homepage.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_multiple_product' not found. 'delete_multiple_product' is not a valid view function or pattern name.
2023-05-15 12:46:03,266 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:46:11,055 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:46:11,637 INFO Watching for file changes with StatReloader
2023-05-15 12:46:14,250 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/urls.py changed, reloading.
2023-05-15 12:46:14,814 INFO Watching for file changes with StatReloader
2023-05-15 12:46:26,620 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:46:27,186 INFO Watching for file changes with StatReloader
2023-05-15 12:46:29,701 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:46:31,359 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:48:25,765 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:48:26,371 INFO Watching for file changes with StatReloader
2023-05-15 12:49:04,672 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:49:05,272 INFO Watching for file changes with StatReloader
2023-05-15 12:49:08,542 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:25,193 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:49:25,777 INFO Watching for file changes with StatReloader
2023-05-15 12:49:33,456 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:49:34,030 INFO Watching for file changes with StatReloader
2023-05-15 12:49:35,419 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:35,714 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:35,914 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:36,026 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:36,254 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:36,434 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:36,630 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:36,770 ERROR Internal Server Error: /front/productlist1/
Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view frontapp.views.ProductList didn't return an HttpResponse object. It returned None instead.
2023-05-15 12:49:59,021 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:49:59,588 INFO Watching for file changes with StatReloader
2023-05-15 12:50:40,816 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:50:41,378 INFO Watching for file changes with StatReloader
2023-05-15 12:52:03,236 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:52:03,878 INFO Watching for file changes with StatReloader
2023-05-15 12:53:37,904 INFO /home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py changed, reloading.
2023-05-15 12:53:38,479 INFO Watching for file changes with StatReloader
2023-05-15 12:54:09,236 WARNING Not Found: /front/forgot-password/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
2023-05-15 12:55:10,456 ERROR Internal Server Error: /front/change_password/16814276-6903-4f92-a452-ab61ae09c85a
Traceback (most recent call last):
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 212, in change_password_with_token
    user_id_instence = User.objects.get(id=request.user.id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 253, in change_password_with_token
    save_exception_to_database(request.user.id, "40", type(e), str(e), ip_address)
  File "/home/simprosys-aman/Aman/Aman/Practical/Shopify/frontapp/views.py", line 51, in save_exception_to_database
    user_id_instence = User.objects.get(id=user_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simprosys-aman/.local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
